### ISSUE TITLE
Add good multiple language support

### ISSUE THREAD

**Issue by ftyers** [d33tah/commonvoice-languagelearning#18]
Currently it allows choosing a different language at startup, but it would be cool if the same server could serve multiple languages.

**Comment by d33tah** [comment]
This would greatly synergize with #26.

**Comment by d33tah** [comment]
Also I feel that #19 would greatly improve the situation here - if I could e.g. assign a bounded difficulty score to all items, storing them in SQLite and then looking up would be much easier.

**Comment by d33tah** [comment]
@ftyers I took a stab at the problem, along with #26. Let me know what you think of the solution and reopen the issue / create a new one if there are things that need improving.
