### ISSUE TITLE
Add a beginner mode that is just pick the right one out of two

### ISSUE THREAD

**Issue by ftyers** [d33tah/commonvoice-languagelearning#25]
Play the audio and present two sentences and the user has to pick the right one.

**Comment by d33tah** [comment]
I like the concept of distractor and the levenshtein distance as first heuristic! Once we abstract it away we could have other ways of electing distractors.

**Comment by ftyers** [comment]
I added a WIP about this, but got stuck on dealing with two AJAX requests at the same time. E.g. you need to know the sentence in order to choose the distractor, but you need to know the distractor in order to build the sentence. And at the moment we're not storing the sentence anywhere except inside the HTML and inside the AJAX response call.

**Comment by ftyers** [comment]
Ok, this is now done.

**Comment by ftyers** [comment]
Ok, now it's done: b86f1d1.
